name: Samsung SM8250 Kernel Build

on:
  workflow_dispatch:
    inputs:
      Option:
        description: 'What do you want build option?'
        required: true
        type: choice
        options:
          - ksun
          - twrp
          - stock  

jobs:
  build:
    strategy:
      matrix:
        device: [x1q, y2q, z3q, c1q, c2q, r8q]
    runs-on: ubuntu-22.04

    steps:
      - name: Install required package
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git libssl-dev bc flex bison \
            libncurses5-dev libncurses-dev libtinfo5 cpio zip unzip \
            python3 curl rsync kmod libelf-dev \
            lz4 tar openssl python3-pip \
            gcc clang        

      - name: "Import kernel source"
        uses: actions/checkout@v4    
        with:
          repository: GoRhanHee/kernel_samsung_sm8250_common
          token: ${{ secrets.REPO_TOKEN }} 

      - name: "Setting permission"
        run: chmod +x build.sh

      - name: "Build for specific device"
        run: ./build.sh ${{ matrix.device }} ${{ github.event.inputs.Option }}

      - name: Upload to GoFile with KernelSU/Stock
        if: github.event.inputs.Option == 'ksun' || github.event.inputs.Option == 'stock'
        run: |
          TARGET_FILE="prebuilts/output/${{ matrix.device }}_Kernel_Odin.tar"
          RESPONSE=$(curl -s -F "file=@$TARGET_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" "https://upload-eu-par.gofile.io/uploadFile")
          echo "Uploaded successfully! Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'

      - name: Upload to GoFile with TWRP
        if: github.event.inputs.Option == 'twrp'
        run: |
          TARGET_FILE="prebuilts/output/${{ matrix.device }}_TWRP_Kernel.zip"
          RESPONSE=$(curl -s -F "file=@$TARGET_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" "https://upload-eu-par.gofile.io/uploadFile")
          echo "Uploaded successfully! Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'             
